baseURL = 'https://wyemake.co.uk'
languageCode = 'en-gb'
pagination.pagerSize = 6
theme= "coHub"
title = 'Wye Make'
 
[Menu]
  # Main Menu
#  [[menu.Main]]
#  name = "About Us"
#  url= "#gallery"
#  weight = 1
  [[menu.Main]]
  name = "Wye Us?"
  url= "#service"
  weight = 1
#  [[menu.Main]]
#  name = "Blog"
#  url= "#blog"
#  weight = 4
  [[menu.Main]]
  name = "Membership"
  url= "#pricing"
  weight = 2
  [[menu.Main]]
  name = "FAQ"
  url= "#faq"
  weight = 3
#  [[menu.Main]]
#  name = "Contact"
#  url= "/contact/"
#  weight = 7

  # Sitemap Menu
  [[menu.sitemap]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 1
  [[menu.sitemap]]
  name = "Terms"
  url = "/terms/"
  weight = 2

[params]
  aboutPageURL = "/"
  contactLink = "/"
  copyright = "© {year} <a href=\"https://wyemake.co.uk/\" target=\"_blank\">Wye Make</a>"
  fabFormURL =  "https://fabform.io/f/u00kv3-"
  googleAnalytics = "G-JZ95FEWF9K"
  logo = "images/logo.png"
  footerlogo = "images/logo.png"
  footerDescription = "Tackling rural isolation in the creative community all along the Wye Valley"

  [params.address]
  address = "Overmonnow Family Learning Centre<br>Monmouth, NP25 5AR"
  email = "hello@wyemake.co.uk"
  openingDesc = "Open on the first and third Tuesdays of each month"
  openingHours = "Between 7:30pm and 9:30pm"
  phone = ""
  w3w = "https://what3words.com/craft.shampoo.unicorns"

  [params.map]
  APIkey = "AIzaSyDege-HGP-PONAUfDqomlq4FvCrKxS1KeE"
  latitude = "51.8067597"
  longitude = "-2.7260575"
  pinImage = "images/pin.png"

  # Socail icons
  [[params.social]]
  icon = "ti-comments"
  url = "https://www.wyemake.co.uk/discord"
  weight = 1
  [[params.social]]
  icon = "ti-github"
  url = "https://github.com/wyemake"
  weight = 2
#  [[params.social]]
#  icon = "ti-dribbble"
#  url = "https://dribbble.com/"
#  weight = 3
#  [[params.social]]
#  icon = "ti-instagram"
#  url = "https://www.instagram.com/"
#  weight = 4
  
  
